# PersistentVolume for PostgreSQL database
# Used for: Hive Metastore backend
# Size: 5Gi (sufficient for testing)
#
# This is a testing-only workaround for minikube (WSL2 + docker driver)
# where dynamic provisioning doesn't work.
#
# Production: Use cloud-specific StorageClass (AWS EBS, Azure Disk, etc.)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: spark
    app.kubernetes.io/testing: "true"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/spark-testing/postgresql
    type: DirectoryOrCreate
