#!/usr/bin/env python3
"""
HTML CSS styles for test report.

This module contains CSS style definitions for HTML reports.
"""

from typing import Dict


def get_css_styles() -> Dict[str, str]:
    """Get CSS styles as dictionary for dynamic use."""
    return {
        "passed_bg": "#d4edda",
        "passed_color": "#155724",
        "failed_bg": "#f8d7da",
        "failed_color": "#721c24",
        "skipped_bg": "#fff3cd",
        "skipped_color": "#856404",
        "total_bg": "#e2e3e5",
        "total_color": "#383d41",
    }


def get_status_color(status: str) -> str:
    """Get background color for status."""
    colors = {
        "passed": "#d4edda",
        "failed": "#f8d7da",
        "skipped": "#fff3cd",
        "error": "#f5c6cb",
    }
    return colors.get(status, "#e2e3e5")


def get_status_text_color(status: str) -> str:
    """Get text color for status."""
    colors = {
        "passed": "#155724",
        "failed": "#721c24",
        "skipped": "#856404",
        "error": "#721c24",
    }
    return colors.get(status, "#383d41")


def get_html_head() -> str:
    """Generate HTML head section with CSS styles."""
    return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spark K8s Test Report</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; margin: 0; padding: 20px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #333; margin-bottom: 5px; }
        .subtitle { color: #666; margin-bottom: 20px; font-size: 14px; }
        .summary { display: flex; gap: 15px; margin: 20px 0; flex-wrap: wrap; }
        .metric { background: #f5f5f5; padding: 20px; border-radius: 6px; flex: 1; min-width: 120px; text-align: center; }
        .metric h3 { margin: 0 0 10px 0; font-size: 14px; color: #666; text-transform: uppercase; }
        .metric .value { font-size: 36px; font-weight: bold; margin: 5px 0; }
        .metric.passed { background: #d4edda; color: #155724; }
        .metric.failed { background: #f8d7da; color: #721c24; }
        .metric.skipped { background: #fff3cd; color: #856404; }
        .metric.total { background: #e2e3e5; color: #383d41; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
        th, td { padding: 12px 10px; text-align: left; border-bottom: 1px solid #dee2e6; }
        th { background: #f8f9fa; font-weight: 600; color: #495057; position: sticky; top: 0; }
        tr:hover { background: #f8f9fa; }
        .status-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
        .status-passed { background: #d4edda; color: #155724; }
        .status-failed { background: #f8d7da; color: #721c24; }
        .status-skipped { background: #fff3cd; color: #856404; }
        .status-error { background: #f5c6cb; color: #721c24; }
        .details { font-size: 12px; color: #6c757d; max-width: 400px; }
        .duration { color: #6c757d; font-size: 12px; }
        .overall-status { padding: 15px; border-radius: 6px; margin-bottom: 20px; text-align: center; font-size: 18px; font-weight: bold; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; font-size: 12px; }
    </style>
</head>
<body>
"""


def get_html_body_end() -> str:
    """Generate HTML body end section."""
    return """            </tbody>
        </table>

        <div class="footer">
            <p>Generated by Spark K8s Test Framework</p>
        </div>
    </div>
</body>
</html>
"""
