apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: dataops
  labels:
    app: spark-master
spec:
  type: ClusterIP
  ports:
    - port: 7077
      targetPort: 7077
      protocol: TCP
      name: spark
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: webui
  selector:
    app: spark-master

