apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: dataops
  labels:
    app: spark-worker
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: webui
  selector:
    app: spark-worker

