#!/bin/bash
# Runbook Accuracy Report Generator
# Generates reports on runbook accuracy and testing results

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNBOOK_DIR="${RUNBOOK_DIR:-/home/fall_out_bug/work/s7/spark_k8s/docs/operations/runbooks}"
OUTPUT="${OUTPUT:-runbook-accuracy-report.md}"

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Generate runbook accuracy report.

OPTIONS:
    -d, --runbook-dir DIR    Runbook directory (default: docs/operations/runbooks)
    -o, --output FILE        Output file (default: runbook-accuracy-report.md)
    -p, --period PERIOD      Report period (default: monthly)
    -h, --help               Show this help

EXAMPLES:
    $(basename "$0") --period monthly
    $(basename "$0") -o /tmp/report.md
EOF
    exit 1
}

PERIOD="monthly"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--runbook-dir)
                RUNBOOK_DIR="$2"
                shift 2
                ;;
            -o|--output)
                OUTPUT="$2"
                shift 2
                ;;
            -p|--period)
                PERIOD="$2"
                shift 2
                ;;
            -h|--help)
                usage
                ;;
            *)
                echo "Unknown option: $1"
                usage
                ;;
        esac
    done
}

count_runbooks() {
    find "$RUNBOOK_DIR" -name "*.md" | wc -l
}

count_tested_runbooks() {
    # Check for test results
    find "$RUNBOOK_DIR" -name "*.md" -exec grep -l "Test Result:" {} \; | wc -l
}

calculate_accuracy() {
    local total=$1
    local passed=$2

    if [[ $total -eq 0 ]]; then
        echo "0"
    else
        echo "scale=2; ($passed / $total) * 100" | bc
    fi
}

generate_report() {
    cat > "$OUTPUT" <<EOF
# Runbook Accuracy Report

**Period**: $PERIOD
**Generated**: $(date)
**Runbook Directory**: $RUNBOOK_DIR

## Summary

| Metric | Count |
|--------|-------|
| Total Runbooks | $(count_runbooks) |
| Tested Runbooks | $(count_tested_runbooks) |
| Accuracy Rate | $(calculate_accuracy $(count_runbooks) $(count_tested_runbooks))% |
| Target Accuracy | >90% |

## Runbook Status

$(list_runbook_status)

## Test Results

$(list_test_results)

## Issues Found

$(list_issues)

## Recommendations

$(generate_recommendations)

## Next Steps

- [ ] Review failed runbooks
- [ ] Update inaccurate runbooks
- [ ] Schedule re-test for updated runbooks
- [ ] Continue monthly testing cycle

---

*Report generated by $(basename "$0")*
EOF
}

list_runbook_status() {
    echo "| Runbook | Status | Last Tested | Accuracy |"
    echo "|---------|--------|------------|----------|"

    find "$RUNBOOK_DIR" -name "*.md" -type f | while read -r runbook; do
        local name=$(basename "$runbook" .md)
        local status="Not Tested"

        # Check if runbook has been tested
        if grep -q "Test Result:" "$runbook"; then
            status=$(grep "Test Result:" "$runbook" | tail -1 | sed 's/.*Test Result: //')
        fi

        # Get last tested date
        local last_tested="Never"
        if grep -q "Last Tested:" "$runbook"; then
            last_tested=$(grep "Last Tested:" "$runbook" | tail -1 | sed 's/.*Last Tested: //')
        fi

        # Get accuracy score
        local accuracy="N/A"
        if grep -q "Accuracy Score:" "$runbook"; then
            accuracy=$(grep "Accuracy Score:" "$runbook" | tail -1 | sed 's/.*Accuracy Score: //' | sed 's/%//')
        fi

        echo "| $name | $status | $last_tested | ${accuracy}% |"
    done
}

list_test_results() {
    echo "### Test Results Summary"
    echo ""

    find "$RUNBOOK_DIR" -name "*.md" -type f -exec grep -l "Test Result:" {} \; | while read -r runbook; do
        local name=$(basename "$runbook" .md)
        local result=$(grep "Test Result:" "$runbook" | tail -1 | sed 's/.*Test Result: //')
        local accuracy=$(grep "Accuracy Score:" "$runbook" | tail -1 | sed 's/.*Accuracy Score: //' | sed 's/%//')

        echo "#### $name"
        echo "- Status: $result"
        echo "- Accuracy: ${accuracy}%"
        echo ""
    done
}

list_issues() {
    echo "### Issues Found During Testing"
    echo ""

    local issues=0

    find "$RUNBOOK_DIR" -name "*.md" -type f | while read -r runbook; do
        if grep -q "### Issues Found" "$runbook"; then
            local name=$(basename "$runbook" .md)
            echo "#### $name"
            awk '/### Issues Found/,/### Recommendations/' "$runbook" | grep -v "###" | grep -v "^$"
            echo ""
            issues=$((issues + 1))
        fi
    done

    if [[ $issues -eq 0 ]]; then
        echo "No issues found."
    fi
}

generate_recommendations() {
    echo "1. **Runbooks Needing Updates**:"
    local need_update=$(find "$RUNBOOK_DIR" -name "*.md" -exec grep -l "Test Result: FAIL" {} \; | wc -l)
    if [[ $need_update -gt 0 ]]; then
        echo "   - $need_update runbooks failed testing and need updates"
    fi

    echo ""
    echo "2. **Untested Runbooks**:"
    local untested=$(find "$RUNBOOK_DIR" -name "*.md" | wc -l)
    local tested=$(find "$RUNBOOK_DIR" -name "*.md" -exec grep -l "Test Result:" {} \; | wc -l)
    echo "   - $((untested - tested)) runbooks have not been tested"

    echo ""
    echo "3. **Accuracy Improvements**:"
    local avg_accuracy=$(find "$RUNBOOK_DIR" -name "*.md" -exec grep -h "Accuracy Score:" {} \; | sed 's/.*Accuracy Score: //' | sed 's/%//' | awk '{s+=$1; n++} END {if(n>0) print s/n; else print 0}')
    if [[ $(echo "$avg_accuracy < 90" | bc) -eq 1 ]]; then
        echo "   - Current accuracy: ${avg_accuracy}%"
        echo "   - Target accuracy: >90%"
        echo "   - Action: Focus on improving low-accuracy runbooks"
    else
        echo "   - Accuracy target met! Current: ${avg_accuracy}%"
    fi
}

main() {
    parse_args "$@"

    echo "Generating runbook accuracy report..."
    echo "Runbook directory: $RUNBOOK_DIR"
    echo "Output file: $OUTPUT"
    echo ""

    generate_report

    echo "Report saved to: $OUTPUT"
}

main "$@"
