#!/bin/bash
# PIR Action Item Tracker
# Tracks and reports on PIR action items

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIR_DIR="/home/fall_out_bug/work/s7/spark_k8s/docs/operations/reports/pira"

usage() {
    cat <<EOF
Usage: $(basename "$0") [ACTION] [OPTIONS]

Track and report on PIR action items.

ACTIONS:
    list                    List all action items from PIRs
    add                     Add a new action item
    update                  Update an action item status
    report                  Generate action item report
    overdue                 List overdue action items

OPTIONS:
    -p, --pir ID            PIR ID (e.g., PIR-123)
    -a, --action ID         Action item ID
    -s, --status STATUS     Status: pending|in-progress|completed
    -o, --owner NAME        Action item owner
    -d, --due DATE          Due date (YYYY-MM-DD)
    -h, --help              Show this help

EXAMPLES:
    $(basename "$0") list
    $(basename "$0") add --pir PIR-123 --title "Fix memory limits" --owner @sre
    $(basename "$0") update --action 1 --status completed
    $(basename "$0") report --output actions-report.md
EOF
    exit 1
}

list_actions() {
    echo "=== PIR Action Items ==="
    echo ""

    # Find all PIR documents
    find "$PIR_DIR" -name "PIRA-*.md" -type f | while read -r pir_file; do
        local pir_id=$(basename "$pir_file" .md | sed 's/PIRA-//')
        local pir_title=$(grep "^# PIR:" "$pir_file" | sed 's/^# PIR: //')

        echo "PIR: $pir_id - $pir_title"
        echo ""

        # Extract action items
        awk '/^### (High|Medium|Low) Priority/,/^###/' "$pir_file" | \
        grep -E '^\- \[ \]' | sed 's/^\- \[ \] \*\*/- /' | sed 's/\*\* (Owner:/ (Owner:/' | \
        while read -r action; do
            if [[ -n "$action" ]]; then
                echo "  $action"
            fi
        done

        echo ""
    done
}

add_action() {
    local pir_id="$1"
    local title="$2"
    local owner="${3:-TBD}"
    local due="${4:-TBD}"

    local pir_file="${PIR_DIR}/PIRA-${pir_id}.md"

    if [[ ! -f "$pir_file" ]]; then
        echo "Error: PIR $pir_id not found at $pir_file"
        exit 1
    fi

    # Find the action items section and append
    # This is a simple implementation; could be more sophisticated
    echo "- [ ] **${title}** (Owner: ${owner}, Due: ${due})" >> "$pir_file"

    echo "Action item added to PIR $pir_id"
    echo "  Title: $title"
    echo "  Owner: $owner"
    echo "  Due: $due"
}

update_action() {
    local action_id="$1"
    local status="$2"

    # Find and update the action item
    # This is a placeholder - would need proper parsing
    echo "Updating action $action_id to status: $status"
    echo "Note: This requires PIR file parsing implementation"
}

generate_report() {
    local output="${1:-actions-report.md}"

    cat > "$output" <<EOF
# PIR Action Items Report

Generated: $(date)

## Summary

| PIR ID | Total Actions | Completed | Pending | Overdue |
|--------|---------------|-----------|---------|---------|
| $(calculate_summary) |

## Action Items by PIR

$(list_actions_by_pir)

## Overdue Actions

$(list_overdue)

---

*Report generated by $(basename "$0")*
EOF

    echo "Report generated: $output"
}

list_overdue() {
    local today=$(date +%Y-%m-%d)

    echo "=== Overdue Action Items ==="
    echo ""

    find "$PIR_DIR" -name "PIRA-*.md" -type f | while read -r pir_file; do
        local pir_id=$(basename "$pir_file" .md | sed 's/PIRA-//')

        # Extract action items and check due dates
        awk '/^\- \[ \]/' "$pir_file" | while read -r action; do
            local due=$(echo "$action" | grep -oP 'Due: \K[0-9-]+')
            if [[ -n "$due" ]] && [[ "$due" < "$today" ]]; then
                local title=$(echo "$action" | sed 's/^\- \[ \] \*\*//' | sed 's/\*\*.*//')
                local owner=$(echo "$action" | grep -oP 'Owner: \K[^,)]+')
                echo "  PIR $pir_id: $title (Owner: $owner, Due: $due)"
            fi
        done
    done
}

calculate_summary() {
    # Placeholder for summary calculation
    echo "Calculating summary..."
}

list_actions_by_pir() {
    find "$PIR_DIR" -name "PIRA-*.md" -type f | while read -r pir_file; do
        local pir_id=$(basename "$pir_file" .md | sed 's/PIRA-//')
        echo "### PIR $pir_id"
        echo ""
        list_pir_actions "$pir_file"
        echo ""
    done
}

list_pir_actions() {
    local pir_file="$1"
    local pir_id=$(basename "$pir_file" .md | sed 's/PIRA-//')

    awk '/^### (High|Medium|Low) Priority/,/^###/' "$pir_file" | \
    grep -E '^\- \[[ x]\]' | sed 's/^\- /- /' | \
    while read -r action; do
        if [[ -n "$action" ]]; then
            echo "  $action"
        fi
    done
}

main() {
    local action="${1:-list}"
    shift || true

    case "$action" in
        list)
            list_actions
            ;;
        add)
            add_action "$@"
            ;;
        update)
            update_action "$@"
            ;;
        report)
            generate_report "$@"
            ;;
        overdue)
            list_overdue
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown action: $action"
            echo ""
            usage
            ;;
    esac
}

main "$@"
