{{- if and .Values.standalone.enabled .Values.standalone.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.standalone.serviceAccount.name | default (printf "%s-standalone" .Release.Name) }}
  labels:
    {{- include "spark-3.5.labels" . | nindent 4 }}
    app.kubernetes.io/component: standalone
  {{- with .Values.standalone.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
