apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub
  namespace: dataops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-spawner
  namespace: dataops
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-spawner
  namespace: dataops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub-spawner
subjects:
  - kind: ServiceAccount
    name: jupyterhub
    namespace: dataops

