{
 "title": "Airflow cluster dashboard",
 "description": "Dashboard for Airflow 2.9.0",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_heartbeat{container=\"statsd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_dagbag_size" }
   ]
  },
  {
   "title": "DAG processing total parse time",
   "type": "stat",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_total_parse_time{}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_ti_failures{airflow_id=~\"$airflow_id\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_ti_successes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Operator success rate per minuite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(airflow_operator_successes[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator failure rate per minute",
   "type": "timeseries",
   "description": "Total failures of given operator",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_ti_finish_test_bash_operator_bash_task_upstream_failed{}",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_queued_tasks{airflow_id=~\"$airflow_id\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Executor Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs started per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(airflow_job_start{}[1m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor open slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots{}" }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_running_tasks{airflow_id=~\"$airflow_id\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs ended per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(airflow_job_end{}[1m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "DAG stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success{}",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "timeseries",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "airflow_dagrun_duration{}", "legendFormat": "{{dag_id}} p{{quantile}}" }
   ]
  },
  {
   "title": "DAG run bash operator dependency check time",
   "type": "timeseries",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check_test_bash_operator{}",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run schedule delay",
   "type": "timeseries",
   "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_dagrun_schedule_delay{} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  }
 ]
}